with open("noxton/nn/xlstm.py", "r") as f:
    content = f.read()

replacements = {
    '"""Computes the sLSTM pointwise gates and updates the cell states (y, c, n, m)."""': '"""Computes the sLSTM pointwise gates and updates the cell states.\n    \n    This function implements the core pointwise operations of the scalar LSTM (sLSTM) cell. \n    It takes the raw input projections and previous states to compute the input, forget, \n    and output gates, as well as the new cell state (c), normalizer state (n), and memory \n    state (m).\n    \n    Args:\n        raw: The raw input projections of shape (hidden_dim * 4,).\n        states: A tuple containing the previous states (y, c, n, m).\n        \n    Returns:\n        A tuple containing the new states (y, c, n, m) and the computed gates.\n    """',
    '"""Executes a single recurrent step of the sLSTM cell, updating states and computing outputs."""': '"""Executes a single recurrent step of the sLSTM cell.\n    \n    This function computes the linear recurrent step for the sLSTM cell given the inputs\n    at the current timestep, the recurrent weights, biases, and previous states. It applies\n    the recurrent projection and then delegates to `slstm_pointwise` to update the cell states.\n    \n    Args:\n        Wx_t: The input projection for the current timestep.\n        states: The previous states of the cell.\n        R: The recurrent kernel weights.\n        b: The recurrent biases.\n        \n    Returns:\n        A tuple containing the updated cell states and the output of the cell at this timestep.\n    """',
    '"""Applies the sLSTM recurrent step across an entire sequence using a jax.lax.scan operation."""': '"""Applies the sLSTM recurrent step across an entire sequence.\n    \n    This function utilizes `jax.lax.scan` to efficiently apply the `slstm_recurrent_step`\n    across a sequence of inputs. This is the preferred method for processing full sequences\n    during training or batch evaluation.\n    \n    Args:\n        Wx_seq: The sequence of input projections over time.\n        states: The initial states of the cell.\n        R: The recurrent kernel weights.\n        b: The recurrent biases.\n        \n    Returns:\n        A tuple containing the sequence of outputs and the final cell states after processing \n        the entire sequence.\n    """',
    '"""Computes the parallel stabilized matrix LSTM (mLSTM) mixing operation over a sequence."""': '"""Computes the parallel stabilized matrix LSTM (mLSTM) mixing operation.\n    \n    This function performs the parallel mixing of queries, keys, and values using the \n    stabilized formulation of the mLSTM cell. It avoids sequential recurrence by computing\n    the mixing via associative prefix sums or cumulative operations on the gates, heavily \n    relying on parallel hardware for efficient execution.\n    \n    Args:\n        queries: The projected query vectors.\n        keys: The projected key vectors.\n        values: The projected value vectors.\n        igate_preact: Pre-activations for the input gate.\n        fgate_preact: Pre-activations for the forget gate.\n        lower_triangular_matrix: Optional causal mask matrix.\n        stabilize_rowwise: Whether to apply row-wise stabilization to avoid overflow.\n        eps: Small constant for numerical stability.\n        **kwargs: Additional keyword arguments.\n        \n    Returns:\n        The output sequence after applying the parallel mLSTM mixing.\n    """',
    '"""Executes a single stabilized recurrent step for the matrix LSTM (mLSTM) formulation."""': '"""Executes a single stabilized recurrent step for the matrix LSTM (mLSTM).\n    \n    This function computes a single timestep update for the mLSTM cell using the \n    recurrent formulation. It updates the covariance matrix state (c_state), normalizer\n    state (n_state), and maximum state (m_state) to compute the cell\'s output. This is\n    typically used during autoregressive inference where parallel processing is not possible.\n    \n    Args:\n        c_state: The covariance matrix state.\n        n_state: The normalizer state.\n        m_state: The maximum state used for stabilization.\n        q: The projected query vector for the current timestep.\n        k: The projected key vector for the current timestep.\n        v: The projected value vector for the current timestep.\n        igate_preact: Pre-activation for the input gate.\n        fgate_preact: Pre-activation for the forget gate.\n        eps: Small constant for numerical stability.\n        **kwargs: Additional keyword arguments.\n        \n    Returns:\n        A tuple containing the output at this timestep and the updated tuple of states.\n    """',
    '"""A Matrix Long Short-Term Memory (mLSTM) cell module."""': '"""A Matrix Long Short-Term Memory (mLSTM) cell module.\n\n    The mLSTM cell represents the memory mechanism using a covariance matrix rather than\n    a scalar cell state. It allows for highly parallelizable training and large memory\n    capacity. This module manages the internal gates, layer normalizations, and can operate\n    both over full sequences in parallel and step-by-step for inference.\n    """',
    '"""Processes a full sequence of queries, keys, and values in parallel."""': '"""Processes a full sequence of queries, keys, and values in parallel.\n        \n        This method invokes the parallel stabilized formulation of the mLSTM to \n        efficiently process entire sequences at once, bypassing the sequential bottleneck\n        of standard recurrent neural networks.\n        \n        Args:\n            q: The input sequence of queries.\n            k: The input sequence of keys.\n            v: The input sequence of values.\n            \n        Returns:\n            The sequence of cell outputs after mixing and applying layer normalization.\n        """',
    '"""Processes a single timestep for the cell, updating and returning the states."""': '"""Processes a single timestep for the cell.\n        \n        This method updates the cell state and computes the output for a single input timestep.\n        It is mainly utilized during autoregressive generation where inputs are provided one by one.\n        \n        Args:\n            q: The query vector for a single timestep.\n            k: The key vector for a single timestep.\n            v: The value vector for a single timestep.\n            cell_state: The previous states of the cell. If None, initializes new empty states.\n            \n        Returns:\n            A tuple containing the cell output for this timestep and the updated cell states.\n        """',
    '"""Initializes and returns the empty initial states for the module."""': '"""Initializes and returns the empty states for the module.\n        \n        Returns:\n            A tuple of tensors initialized to zero, representing the initial covariance matrix,\n            normalizer state, and maximum state.\n        """',
    '"""A complete mLSTM layer, incorporating up-projections, down-projections, and an optional 1D causal convolution."""': '"""A complete mLSTM layer block.\n\n    This module encapsulates a full mLSTM block, which includes an initial up-projection\n    into an inner embedding dimension, a 1D causal convolution for local mixing, \n    the core `mLSTMCell` for sequence mixing, an output gate branch, and a final \n    down-projection back to the original embedding dimension. It behaves as a complete\n    sub-layer within a larger transformer-like architecture.\n    """',
    '"""Performs a forward pass of the layer over an entire input sequence."""': '"""Performs a forward pass of the layer over an entire input sequence.\n        \n        This method processes the input sequence through the up-projection, causal \n        convolution, parallel mLSTM cell, and down-projection.\n        \n        Args:\n            x: The input sequence of embeddings.\n            key: PRNG key for dropout operations.\n            \n        Returns:\n            The output sequence after passing through the full layer.\n        """',
    '"""Performs a single step forward pass, commonly used during autoregressive generation."""': '"""Performs a single step forward pass.\n        \n        Executes a single step update of the layer, including the stateful 1D convolution \n        and the stateful mLSTM cell. This is primarily used for autoregressive decoding.\n        \n        Args:\n            x: The input embedding for a single timestep.\n            cell_state: The previous states of the mLSTM cell.\n            conv_state: The previous states of the 1D causal convolution.\n            key: PRNG key for dropout.\n            \n        Returns:\n            A tuple containing the output embedding for this timestep and the updated tuples \n            of cell and convolution states.\n        """',
    '"""Initializes and returns the empty state tuples for both the cell and the 1D convolution."""': '"""Initializes and returns the empty states for the layer.\n        \n        Returns:\n            A tuple containing the initial states for both the internal `mLSTMCell` and the `CausalConv1d`.\n        """',
    '"""A Scalar Long Short-Term Memory (sLSTM) cell module."""': '"""A Scalar Long Short-Term Memory (sLSTM) cell module.\n\n    The sLSTM cell acts as a more traditional LSTM cell but with stabilized exponential \n    gating and normalization. It relies on sequential processing and maintains a scalar \n    memory state per hidden dimension, updated via standard recurrence.\n    """',
    '"""Processes an entire sequence of inputs through the cell."""': '"""Processes an entire sequence of inputs through the cell.\n        \n        This method utilizes `jax.lax.scan` internally to efficiently compute the \n        recurrent updates across the entire sequence.\n        \n        Args:\n            x: The sequence of projected inputs.\n            state: The initial states of the cell. If None, initializes empty states.\n            \n        Returns:\n            A tuple containing the sequence of outputs and the final cell states.\n        """',
    '"""A complete sLSTM layer implementation, featuring input gating and an optional 1D causal convolution."""': '"""A complete sLSTM layer implementation.\n\n    This layer wraps the `sLSTMCell` with optional 1D causal convolution and computes\n    the necessary projections for the input, forget, output, and update gates. It serves\n    as a complete sub-layer component for sequential data modeling.\n    """',
    '"""An extended LSTM (xLSTM) residual block, which wraps an mLSTM or sLSTM layer with optional feed-forward networks and layer normalization."""': '"""An extended LSTM (xLSTM) residual block.\n\n    This module encapsulates an entire xLSTM block, consisting of a core xLSTM layer \n    (either an `mLSTMLayer` or an `sLSTMLayer`) followed by an optional feed-forward network (FFN). \n    It applies pre-layer normalization and residual connections around both the xLSTM \n    layer and the FFN, forming a complete building block for deep xLSTM architectures.\n    """',
    '"""Initializes and returns the underlying states for the recurrent layers within the block."""': '"""Initializes and returns the underlying states for the block.\n        \n        Delegates the state initialization to the underlying xLSTM layer.\n        \n        Returns:\n            The initial states for the components within the block.\n        """',
}

# The __call__ and step strings are duplicated across mLSTM, sLSTM, xLSTM so I will replace them one by one based on class context or just let them duplicate if they fit all.
# Let's write a smarter regex or state machine replacement in python to target specific classes.
